Create routes
sw7-02/backend pull request #17
Opened 2023-11-15 07:29 UTC by mariusgardshodn

2023-11-15 08:06 UTC, t-lohse requested changes
all in all is good, mangler dog nogle ting udover de kommentarer jeg har sat:
- jeg har løst en opgave, hvordan bliver den smidt i DB?
- jeg har løst en assignment, hvordan bliver den smidt i DB?
- en `:session_id` til at få exercises i en given session?

Jeg har også nogle andre routes, men de er slet ik i MVP, så dem laver jeg som en hygge TODO i filerne senere

2023-11-15 08:06 UTC, t-lohse commented on src/routes/exercise_solutions.ts
> +    return res.sendStatus(200);
Er ret sikker på at der vil være en fejl her, at man ik kan sende 2 gange. Men du behøver ikke at sætte statuskode når det er 200, det er default

2023-11-15 08:06 UTC, t-lohse commented on src/routes/task_view.ts
> +routes.use("/", exercise_solutions);
duplicate `exercise_solution` (se `coures_overview.ts`)

2023-11-15 08:14 UTC, mariusgardshodn commented on src/routes/exercise_solutions.ts
> +    return res.sendStatus(200);
Så der kunne evt. stå "return res.send(req.params);"?

2023-11-15 08:15 UTC, mariusgardshodn commented on src/routes/task_view.ts
> +routes.use("/", exercise_solutions);
glemte at slette fra course_overview..

2023-11-15 08:20 UTC, mariusgardshodn commented on src/routes/index.ts
> +routes.use("/courses", course_overview);
Selvom det er alle courses der menes?

2023-11-15 11:57 UTC, t-lohse requested changes

2023-11-15 11:57 UTC, t-lohse commented on src/routes/signup.ts
> +});
Er der en grund til at de skal `get` signup, vi skal jo bare have at man kan gøre det?

2023-11-15 11:57 UTC, t-lohse commented on src/routes/course/course_overview.ts
> +    // TODO: redirect to course overview
det er en frontend opgave, ikke noget en REST API skal/kan håndtere (bare fyi)

2023-11-15 11:57 UTC, t-lohse commented on src/routes/course/course_overview.ts
> +});
exercise relateret, synes den skal være nede i `exercise.ts`

2023-11-15 11:57 UTC, t-lohse commented on src/routes/course/course_overview.ts
> +});
exercise relateret, synes den skal være nede i `exercise.ts`

2023-11-15 11:57 UTC, t-lohse commented on src/routes/course/course_overview.ts
> +routes.use("/:course_id/:session_id/:exercise_id", exercise);
den her burder være i `course/index.ts`

2023-11-15 11:57 UTC, t-lohse commented on src/routes/index.ts
> +routes.use("/login/sign-up", signup);
høre sign-up til under login? hierarkisk giver det ik mening for mig, synes det skal være sin egen

2023-11-15 11:57 UTC, t-lohse commented on src/routes/course/course_overview.ts
> +routes.put("/:course_id/:assignment_id/", (req: Request, res: Response) => {
`assginment.ts`?
`/:course_id/:assignment_id/assignment_solutions`?

2023-11-15 11:57 UTC, t-lohse commented on src/routes/course/course_overview.ts
> +});
yeet `course_overview.ts` og placer i `course/index.ts`

2023-11-15 11:57 UTC, t-lohse commented on src/routes/signup.ts
> +import Router, {Request, Response} from "express"
synes også at `signup` skal ligge under `auth`, det er jo en authorization

2023-11-15 12:12 UTC, t-lohse commented on src/routes/exercise_solutions.ts
> +    return res.sendStatus(200);
du behøver ikke engang return, det er en `Promise<void>`

2023-11-15 12:20 UTC, mariusgardshodn commented on src/routes/signup.ts
> +});
Nej, det er der ikke.. mb

2023-11-15 13:50 UTC, mariusgardshodn commented on src/routes/course/course_overview.ts
> +    // TODO: redirect to course overview
Det var der ellers nogle der gjorde på nettet

2023-11-15 13:51 UTC, mariusgardshodn commented on src/routes/course/course_overview.ts
> +routes.put("/:course_id/:assignment_id/", (req: Request, res: Response) => {
assignments er på samme niveau som sessions, så siden sessions ikke har en fil, så skal assignments nok heller ikke?

2023-11-16 09:07 UTC, t-lohse commented on src/routes/course/assignment.ts
> +});
Tror vi har et lille problem når det kommer til path til assignments og sessions, eftersom deres ID's kan overlappe(?), så maybe have en `/assignment/:assignment_id` path i stedet?

2023-11-16 09:07 UTC, t-lohse commented on src/routes/course/exercise.ts
> +});
vil det her ik være `/course/:session/` som man deleter, burde der ik være en `:exercise` på den? Eller er det ment som man skal sende det i body'en af ens request?

2023-11-16 10:04 UTC, t-lohse submitted a review, later dismissed

2023-11-16 10:09 UTC, t-lohse approved these changes

2023-11-16 10:09 UTC, merged